name: Create GitHub Repo

on:
  workflow_dispatch:
    inputs:
      repo_name: 
        description: 'repo-test-with-pipeline'
        required: true
        type: string

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Create a new GitHub repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NEW_REPO: ${{ github.event.inputs.repo_name }}
        run: |
          echo "Creating new repo: $NEW_REPO"
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user/repos \
            -d "{\"name\":\"$NEW_REPO\"}"
